name: Build Images

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  IMAGE_PREFIX: ghcr.io/kilip/reboot
jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup build tags
        id: tag
        run: |
          date_tag=$(date +'%Y%m%d%H%M%S')

          # php main
          echo "PHP_NIGHTLY=${IMAGE_PREFIX}-php:main-${date_tag}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Build Docker images
      #  uses: docker/bake-action@v4
      #  with:
      #    pull: true
      #    load: true
      #    files: |
      #      compose.yaml
      #      compose.prod.yaml
      #    set: |
      #      *.cache-from=type=gha,scope=${{github.ref}}
      #      *.cache-from=type=gha,scope=refs/heads/main
      #      *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Echo github output tags
        run: |
          echo "nightly ${{ steps.tag.outputs.PHP_NIGHTLY }}"

  