name: Build Images

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  IMAGE_PREFIX: ghcr.io/kilip/reboot
jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup build tags
        id: tag
        run: |
          echo "tag=hello" >> "$GITHUB_OUTPUT"
          echo "foo=bar" >> "$GITHUB_OUTPUT"
      
      - name: Echo github output
        run: |
          echo "the secret number is ${{ steps.tag.outputs.tag }}"
          echo "the secret number is ${{ steps.tag.outputs.foo }}"
