---
name: CI

on:
  push:
    branches: ["main"]

jobs:
  static:
    name: Static Check
    uses: kilip/gh-php-common/.github/workflows/static-check.yaml@main
    with:
      php_version: 8.3
      commitlint: true
      phpstan: true
      phpcsfixer: true
    secrets: inherit
