---
name: CI

on:
  push:
    branches: ["main"]

jobs:
  static:
    name: Static Check
    uses: kilip/gh-common/.github/workflows/php-lint.yaml@main
    with:
      php_version: 8.3
    secrets: inherit
